# Generated by Django 5.2.3 on 2025-06-10 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceAdditionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_km_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daps', to='engine.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_minutes', models.PositiveIntegerField(default=0)),
                ('charge_per_slab', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slab_minutes', models.PositiveIntegerField(default=1)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcs', to='engine.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('up_to_kms', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbps', to='engine.pricingconfig')),
            ],
            options={
                'unique_together': {('config', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='TimeMultiplierSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_minutes', models.PositiveIntegerField()),
                ('to_minutes', models.PositiveIntegerField()),
                ('multiplier', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmfs', to='engine.pricingconfig')),
            ],
            options={
                'unique_together': {('config', 'from_minutes', 'to_minutes')},
            },
        ),
    ]
